# Setup
title: Thomas Cooper
tagline: Ramblings about technology, cloud, Kubernetes and software craftsmanship.
description: >-
  Technology, cloud, Kubernetes and software craftsmanship. Gaming, music and other random stuff.
url: https://blog.coopernetes.ca
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Thomas Cooper
  url:               https://github.com/coopernetes
  email:             me at coopernetes dot ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
github:
  repo: https://github.com/coopernetes/coopernetes.github.io
google_analytics_id: #UA-XXXX-Y
